import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getReplay, getReplays } from "@/lib/replays";
import { Badge, buttonClass, Card, SectionTitle } from "@/components/ui";
import { BotFace } from "@/components/bot-face";

export function generateStaticParams() {
  return getReplays().map((r) => ({ debateId: r.id }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ debateId: string }>;
}): Promise<Metadata> {
  const replay = getReplay((await params).debateId);
  return { title: replay ? `${replay.title} — Watch` : "Replay not found" };
}

export default async function ReplayPage({
  params,
}: {
  params: Promise<{ debateId: string }>;
}) {
  const replay = getReplay((await params).debateId);
  if (!replay) notFound();

  return (
    <div className="mx-auto max-w-3xl px-4 py-10">
      <div className="flex flex-wrap items-center gap-2">
        <Badge tone="info">Simulated exhibition — generated by the mock AI runtime</Badge>
        <Badge>{replay.formatId}</Badge>
      </div>
      <h1 className="mt-3 text-2xl font-extrabold tracking-tight">{replay.title}</h1>
      <p className="mt-1 text-fg-muted">{replay.motionText}</p>

      <div className="mt-5 grid grid-cols-2 gap-3">
        {[
          { name: replay.sideFor, slug: replay.sideForSlug, side: "For" },
          { name: replay.sideAgainst, slug: replay.sideAgainstSlug, side: "Against" },
        ].map((p) => (
          <Card key={p.side} className="p-3 text-center">
            <BotFace slug={p.slug} name={p.name} size={48} className="mx-auto" />
            <p className="mt-1 text-sm font-semibold">{p.name}</p>
            <p className="text-xs text-fg-muted">{p.side}</p>
          </Card>
        ))}
      </div>

      <Card className="mt-5 p-5">
        <SectionTitle>Key clashes</SectionTitle>
        <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-fg-muted">
          {replay.keyClashes.map((c) => (
            <li key={c}>{c}</li>
          ))}
        </ul>
      </Card>

      <SectionTitle className="mt-8">Transcript</SectionTitle>
      <div className="mt-3 space-y-2">
        {replay.transcript.map((t, i) => (
          <div key={i} className="rounded-xl bg-surface-1 p-4 text-sm">
            <p className="text-xs font-semibold text-fg-muted">
              {t.phaseName} · {t.side === "for" ? replay.sideFor : replay.sideAgainst}
            </p>
            <p className="mt-1.5 leading-relaxed">{t.text}</p>
          </div>
        ))}
      </div>

      <Card className="mt-6 border-brand/40 p-5">
        <SectionTitle>Judge commentary</SectionTitle>
        <p className="mt-2 text-sm text-fg-muted">{replay.judgeSummary}</p>
        <p className="mt-3 text-xs text-fg-faint">
          AI-generated educational assessment of a simulated round.
        </p>
      </Card>

      <div className="mt-6 flex justify-between">
        <Link href="/watch" className={buttonClass("ghost", "md")}>
          ← All replays
        </Link>
        <Link href="/bots" className={buttonClass("primary", "md")}>
          Debate one of these bots
        </Link>
      </div>
    </div>
  );
}
